# Generated by Django 4.2.24 on 2025-09-30 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0002_alter_driver_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='user',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Ride',
        ),
    ]
